/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : S32DS_Project_RLM-L
**     Processor   : S32K116_48
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-12-01, 17:18, # CodeGen: 21
**     Abstract    :
**
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/         

/* MODULE pin_mux. */
#include "device_registers.h"
#include "pin_mux.h"

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 11.4, A conversion should not be performed
 * between a pointer to object and an integer type.
 * The cast is required to initialize a pointer with an unsigned int define,
 * representing an address.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 11.6, A cast shall not be performed
 * between pointer to void and an arithmetic type.
 * The cast is required to initialize a pointer with an unsigned int define,
 * representing an address.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 9.3, partial array initialization.
 * The object array is initialized sequentially.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 9.4, Duplicate initialization of object element.
 * The object array is initialized sequentially.
 *
 */

/*! @brief Array of pin configuration structures */

const pin_settings_config_t g_pin_RecoverFactory_InitConfigArr[2] =
{
	
			
		{
        .base          = PORTA,
        .pinPortIdx    = 4u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_INPUT_DIRECTION,
        .digitalFilter = false,
     },
		
		 {
				.base          = PORTC,
				.pinPortIdx    = 4u,
				.pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
				.passiveFilter = false,
				.driveSelect   = PORT_LOW_DRIVE_STRENGTH,
				.mux           = PORT_MUX_AS_GPIO,
				.pinLock       = false,
				.intConfig     = PORT_DMA_INT_DISABLED,
				.clearIntFlag  = false,
				.gpioBase      = PTC,
				.direction     = GPIO_INPUT_DIRECTION,
				.digitalFilter = false,
		},
};

const pin_settings_config_t g_pin_Factory_InitConfigArr[2] =
{
		{
        .base          = PORTA,
        .pinPortIdx    = 4u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
     },
		
		{
        .base          =  PORTC,
        .pinPortIdx    = 4u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           =   PORT_MUX_AS_GPIO,
        .pinLock       =   false,
        .intConfig     =  PORT_DMA_INT_DISABLED,
        .clearIntFlag  =  false,
        .gpioBase      =  PTC,
        .direction     =  GPIO_OUTPUT_DIRECTION,
        .digitalFilter =  false,
        .initValue     =  0u,
    },
};

const pin_settings_config_t g_pin_mux_InitConfigArr[NUM_OF_CONFIGURED_PINS] =
{

//////////////////////////冰箱一档PTC6 /////////////////////////
   {
        .base          =  PORTC,
        .pinPortIdx    = 6u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           =   PORT_MUX_AS_GPIO,
        .pinLock       =   false,
        .intConfig     =  PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTC,
        .direction     =  GPIO_OUTPUT_DIRECTION,
        .digitalFilter =   false,
        .initValue     =  0u,
    },

//////////////////////////冰箱2档PTA13 /////////////////////////
   {
        .base          = PORTA,
        .pinPortIdx    = 13u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
    
//////////////////////////辅助加热PTB4 /////////////////////////
   {
        .base          =   PORTB,
        .pinPortIdx    = 0u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTB,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
//////////////////////////加热PTA0 /////////////////////////
  {
        .base          = PORTA,
        .pinPortIdx    = 0u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
		
 //////////////////////////臭氧PTB1 /////////////////////////
 /*  {
        .base          =   PORTB,
        .pinPortIdx    = 1u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTB,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
		*/
		{
        .base          =   PORTD,
        .pinPortIdx    = 5u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTD,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },

	
//////////////////////////冰箱门PTA1 /////////////////////////
  {
        .base          = PORTA,
        .pinPortIdx    = 1u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
	//////////////////////////工厂模式下的8421码/////////////////////////	 
	 /*
		  
	
	*/
	
		
		{
        .base          = PORTA,
        .pinPortIdx    = 10u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
		{
        .base          =  PORTC,
        .pinPortIdx    = 5u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           =  PORT_MUX_AS_GPIO,
        .pinLock       =  false,
        .intConfig     =  PORT_DMA_INT_DISABLED,
        .clearIntFlag  =  false,
        .gpioBase      =  PTC,
        .direction     =  GPIO_OUTPUT_DIRECTION,
        .digitalFilter =  false,
        .initValue     =  0u,
    },

//////////////////////////LED1  PTD2 /////////////////////////
  {
        .base          = PORTD,
        .pinPortIdx    = 2u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTD,
        .direction     = GPIO_OUTPUT_DIRECTION,//GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },
	
//////////////////////////LED2  PTD3 /////////////////////////
  {
        .base          = PORTD,
        .pinPortIdx    = 3u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTD,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 0u,
    },

//////////////////////////读取冰箱故障码PTc7 /////////////////////////
			{
					.base          = PORTC,
					.pinPortIdx    = 7u,
					.pullConfig    = PORT_INTERNAL_PULL_UP_ENABLED,
					.passiveFilter = false,
					.driveSelect   = PORT_HIGH_DRIVE_STRENGTH,
					.mux           = PORT_MUX_AS_GPIO,
					.pinLock       = false,
					.intConfig     = PORT_DMA_INT_DISABLED,
					.clearIntFlag  = false,
					.gpioBase      = PTC,
					.direction     = GPIO_INPUT_DIRECTION,
					.digitalFilter = false,
			},
	//////////////////////////进入工厂模式的测试点/////////////////////////	 
		 {
        .base          = PORTC,
        .pinPortIdx    = 9u,
        .pullConfig    = PORT_INTERNAL_PULL_UP_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_HIGH_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTC,
        .direction     = GPIO_INPUT_DIRECTION,
        .digitalFilter = false,
    },
		
		{
        .base          = PORTA,
        .pinPortIdx    = 7u,
        .pullConfig    = PORT_INTERNAL_PULL_UP_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_HIGH_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTA,
        .direction     = GPIO_INPUT_DIRECTION,
        .digitalFilter = false,
    },
/////////////////////////////CAN //////////////////////////////////////////

	{
	.base = PORTC,
	.pinPortIdx = 3u,
	.pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED,
	.passiveFilter = false,
	.driveSelect = PORT_LOW_DRIVE_STRENGTH,
	.mux = PORT_MUX_ALT3,
	.pinLock = false,
	.intConfig = PORT_DMA_INT_DISABLED,
	.clearIntFlag = false,
	.gpioBase = NULL,
	.digitalFilter = false,
	},
	{
	.base = PORTC,
	.pinPortIdx = 2u,
	.pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED,
	.passiveFilter = false,
	.driveSelect = PORT_LOW_DRIVE_STRENGTH,
	.mux = PORT_MUX_ALT3,
	.pinLock = false,
	.intConfig = PORT_DMA_INT_DISABLED,
	.clearIntFlag = false,
	.gpioBase = NULL,
	.digitalFilter = false,
	},
//////////////////////////串口 /////////////////////////	

	{
	.base = PORTA,
	.pinPortIdx = 3u,
	.pullConfig = PORT_INTERNAL_PULL_UP_ENABLED,
	.passiveFilter = false,
	.driveSelect = PORT_LOW_DRIVE_STRENGTH,
	.mux = PORT_MUX_ALT6,
	.pinLock = false,
	.intConfig = PORT_DMA_INT_DISABLED,
	.clearIntFlag = false,
	.gpioBase = NULL,
	.digitalFilter = false,
	},
	{
	.base = PORTA,
	.pinPortIdx = 2u,
	.pullConfig = PORT_INTERNAL_PULL_UP_ENABLED,
	.passiveFilter = false,
	.driveSelect = PORT_LOW_DRIVE_STRENGTH,
	.mux = PORT_MUX_ALT6,
	.pinLock = false,
	.intConfig = PORT_DMA_INT_DISABLED,
	.clearIntFlag = false,
	.gpioBase = NULL,
	.digitalFilter = false,
	},
//////////////////////////蜂鸣器 /////////////////////////	
	{
        .base          = PORTD,
        .pinPortIdx    = 16u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTD,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     =  0u,
     },
	  {
			.base = PORTD,
			.pinPortIdx = 15u,
			.pullConfig = PORT_INTERNAL_PULL_NOT_ENABLED,
			.passiveFilter = false,
			.driveSelect = PORT_LOW_DRIVE_STRENGTH,
			.mux = PORT_MUX_ALT2,
			.pinLock = false,
			.intConfig = PORT_DMA_INT_DISABLED,
			.clearIntFlag = false,
			.gpioBase = NULL,
			.digitalFilter = false,
		},
		
    /* new sch. DKLai20230428 */
    { 
        .base          = PORTB,
        .pinPortIdx    = 4u,
        .pullConfig    = PORT_INTERNAL_PULL_NOT_ENABLED,
        .passiveFilter = false,
        .driveSelect   = PORT_LOW_DRIVE_STRENGTH,
        .mux           = PORT_MUX_AS_GPIO,
        .pinLock       = false,
        .intConfig     = PORT_DMA_INT_DISABLED,
        .clearIntFlag  = false,
        .gpioBase      = PTB,
        .direction     = GPIO_OUTPUT_DIRECTION,
        .digitalFilter = false,
        .initValue     = 1u,
    },

};

/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
